import type { Video } from "@/types";

// Demo/seed catalog for Salin Radio's MVP (no YOUTUBE_API_KEY / OPENAI_API_KEY required).
// A handful of entries use real, embeddable YouTube videos so the player and
// autoplay-next logic can be exercised end to end. The rest are fictional
// "discoveries" (invented metadata + placeholder video ids) used to populate
// filters, admin moderation states, and score variety. Once the YouTube Data
// API + AI pipeline are wired up (see src/lib/youtube.ts and src/lib/ai.ts),
// this file stops being the source of truth.

function thumb(youtubeId: string) {
  return `https://i.ytimg.com/vi/${youtubeId}/hqdefault.jpg`;
}

function url(youtubeId: string) {
  return `https://www.youtube.com/watch?v=${youtubeId}`;
}

const now = new Date().toISOString();

export const MOCK_VIDEOS: Video[] = [
  {
    id: "vid-001",
    youtube_video_id: "jNQXAC9IVRw",
    title: "Me at the zoo",
    channel_name: "jawed",
    channel_id: "ch-jawed",
    description:
      "La toute première vidéo jamais publiée sur YouTube, tournée au zoo de San Diego le 23 avril 2005.",
    thumbnail_url: thumb("jNQXAC9IVRw"),
    duration_seconds: 19,
    view_count: 340000000,
    like_count: 15000000,
    published_at: "2005-04-23",
    youtube_url: url("jNQXAC9IVRw"),
    embed_allowed: true,
    status: "approved",
    rarity_score: 30,
    quality_score: 55,
    discovery_score: 92,
    sample_score: 15,
    ai_summary:
      "Le clip fondateur de YouTube : 19 secondes filmées au zoo de San Diego, devenues malgré elles un monument culturel du web.",
    ai_reason:
      "Retenue pour sa valeur archéologique plutôt que pour sa rareté actuelle : c'est le point zéro de toute vidéo en ligne, un repère que Salin Radio garde dans sa rotation nocturne.",
    mood: "nostalgique",
    genre: "archive",
    country: "États-Unis",
    decade: "2000s",
    tags: ["histoire d'internet", "archive", "curiosité"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-002",
    youtube_video_id: "_OBlgSz8sSM",
    title: "Charlie bit my finger - again !",
    channel_name: "HDCYT",
    channel_id: "ch-hdcyt",
    description:
      "Un classique du web 2.0 : deux frères anglais, un doigt mordu, un fou rire devenu planétaire.",
    thumbnail_url: thumb("_OBlgSz8sSM"),
    duration_seconds: 56,
    view_count: 880000000,
    like_count: 6000000,
    published_at: "2007-05-22",
    youtube_url: url("_OBlgSz8sSM"),
    embed_allowed: true,
    status: "approved",
    rarity_score: 20,
    quality_score: 60,
    discovery_score: 80,
    sample_score: 10,
    ai_summary:
      "Une vidéo de famille filmée sans ambition, devenue malgré elle l'un des clips les plus regardés du web.",
    ai_reason:
      "Gardée comme curiosité d'archive plutôt que comme découverte rare : elle illustre comment l'anodin peut devenir culte.",
    mood: "joyeux",
    genre: "home video",
    country: "Royaume-Uni",
    decade: "2000s",
    tags: ["viral", "famille", "archive"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-003",
    youtube_video_id: "YE7VzlLtp-4",
    title: "Big Buck Bunny",
    channel_name: "Blender",
    channel_id: "ch-blender",
    description:
      "Court métrage d'animation open source de la Blender Foundation : un gros lapin se venge de trois rongeurs harceleurs.",
    thumbnail_url: thumb("YE7VzlLtp-4"),
    duration_seconds: 596,
    view_count: 210000000,
    like_count: 900000,
    published_at: "2008-05-10",
    youtube_url: url("YE7VzlLtp-4"),
    embed_allowed: true,
    status: "approved",
    rarity_score: 25,
    quality_score: 85,
    discovery_score: 70,
    sample_score: 40,
    ai_summary:
      "Film d'animation libre et open source, produit par une communauté plutôt qu'un studio — un cas rare de cinéma indépendant totalement transparent.",
    ai_reason:
      "Sélectionnée pour son statut culturel singulier : un film 3D complet distribué librement, hors des circuits commerciaux classiques.",
    mood: "ludique",
    genre: "animation indépendante",
    country: "Pays-Bas",
    decade: "2000s",
    tags: ["cinéma d'animation", "open source", "court métrage"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-004",
    youtube_video_id: "eRsGyueVLvQ",
    title: "Sintel",
    channel_name: "Blender",
    channel_id: "ch-blender",
    description:
      "Film d'animation fantastique en licence libre : une jeune femme part à la recherche d'un dragon qu'elle a élevé.",
    thumbnail_url: thumb("eRsGyueVLvQ"),
    duration_seconds: 888,
    view_count: 95000000,
    like_count: 700000,
    published_at: "2010-09-30",
    youtube_url: url("eRsGyueVLvQ"),
    embed_allowed: true,
    status: "approved",
    rarity_score: 35,
    quality_score: 90,
    discovery_score: 75,
    sample_score: 30,
    ai_summary:
      "Un moyen-métrage mélancolique, porté par une bande-son orchestrale rare pour une production libre de droits.",
    ai_reason:
      "Qualité visuelle et musicale élevée, faible circulation en dehors des cercles techniques — un bon pont entre cinéma d'auteur et culture libre.",
    mood: "mélancolique",
    genre: "animation indépendante",
    country: "Pays-Bas",
    decade: "2010s",
    tags: ["fantastique", "open source", "bande originale"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-005",
    youtube_video_id: "n4KpZ2QxT8s",
    title: "Cassette retrouvée — funk de Lagos, 1978",
    channel_name: "Lagos Tape Archive",
    channel_id: "ch-lagos-archive",
    description:
      "Un enregistrement de session studio non identifié, numérisé depuis une bobine retrouvée à Lagos.",
    thumbnail_url: thumb("n4KpZ2QxT8s"),
    duration_seconds: 247,
    view_count: 1800,
    like_count: 210,
    published_at: "2021-02-14",
    youtube_url: url("n4KpZ2QxT8s"),
    embed_allowed: true,
    status: "approved",
    rarity_score: 88,
    quality_score: 82,
    discovery_score: 90,
    sample_score: 95,
    ai_summary:
      "Groove afrobeat brut, cuivres en avant, probablement enregistré en une seule prise dans un studio local en 1978.",
    ai_reason:
      "Chaîne quasi inconnue, moins de 2000 vues, break rythmique exploitable au sampling : profil idéal de découverte rare.",
    mood: "énergique",
    genre: "funk",
    country: "Nigéria",
    decade: "1970s",
    tags: ["afrobeat", "funk", "potentiel sample"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-006",
    youtube_video_id: "w7VbHq3MzXp",
    title: "Chant de mineurs gallois, enregistrement de 1962",
    channel_name: "Welsh Folk Archive",
    channel_id: "ch-welsh-archive",
    description:
      "Field recording d'un chœur de mineurs gallois, capté lors d'une collecte ethnomusicologique.",
    thumbnail_url: thumb("w7VbHq3MzXp"),
    duration_seconds: 193,
    view_count: 640,
    like_count: 88,
    published_at: "2019-11-02",
    youtube_url: url("w7VbHq3MzXp"),
    embed_allowed: true,
    status: "approved",
    rarity_score: 91,
    quality_score: 76,
    discovery_score: 85,
    sample_score: 40,
    ai_summary:
      "Polyphonie vocale a cappella, ambiance solennelle, typique des chœurs de mine gallois du milieu du XXe siècle.",
    ai_reason:
      "Archive ethnomusicologique rarement vue, contenu culturel fort, cohérence titre/description parfaite.",
    mood: "solennel",
    genre: "field recording",
    country: "Royaume-Uni",
    decade: "1960s",
    tags: ["field recording", "chant traditionnel", "archive"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-007",
    youtube_video_id: "e8LtRq4WkYm",
    title: "Improvisation synthé DIY dans un garage soviétique, 1986",
    channel_name: "Kolkhoz Modular",
    channel_id: "ch-kolkhoz-modular",
    description:
      "Session solo captée en VHS, synthétiseur modulaire fait maison, quelque part en URSS.",
    thumbnail_url: thumb("e8LtRq4WkYm"),
    duration_seconds: 412,
    view_count: 3200,
    like_count: 340,
    published_at: "2020-06-18",
    youtube_url: url("e8LtRq4WkYm"),
    embed_allowed: true,
    status: "approved",
    rarity_score: 95,
    quality_score: 70,
    discovery_score: 93,
    sample_score: 88,
    ai_summary:
      "Textures analogiques hypnotiques, matériel bricolé, ambiance quasi industrielle — un artefact électronique underground.",
    ai_reason:
      "Extrêmement peu vue, hors des radars des recommandations classiques, forte singularité sonore et visuelle.",
    mood: "hypnotique",
    genre: "électronique expérimentale",
    country: "Russie",
    decade: "1980s",
    tags: ["synthé modulaire", "expérimental", "VHS"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-008",
    youtube_video_id: "s2FqNz9LrKt",
    title: "Publicité télé oubliée pour un parc aquatique, 1994",
    channel_name: "VHS Vault",
    channel_id: "ch-vhs-vault",
    description:
      "Spot publicitaire régional retrouvé sur une cassette d'enregistrement TV des années 90.",
    thumbnail_url: thumb("s2FqNz9LrKt"),
    duration_seconds: 31,
    view_count: 950,
    like_count: 60,
    published_at: "2022-03-01",
    youtube_url: url("s2FqNz9LrKt"),
    embed_allowed: true,
    status: "approved",
    rarity_score: 80,
    quality_score: 55,
    discovery_score: 78,
    sample_score: 20,
    ai_summary:
      "Publicité kitsch et volontairement décalée, jingle mémorable, esthétique VHS assumée.",
    ai_reason:
      "Curiosité d'archive télé régionale, quasiment invisible en ligne, bonne valeur nostalgique et étrange.",
    mood: "absurde",
    genre: "archive TV",
    country: "France",
    decade: "1990s",
    tags: ["publicité", "VHS", "nostalgie"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-009",
    youtube_video_id: "u5MxTb2VqRn",
    title: "Set de club underground filmé en VHS, Berlin 1991",
    channel_name: "Ostgut Tapes",
    channel_id: "ch-ostgut-tapes",
    description:
      "Extrait d'une soirée techno filmée en caméscope dans un club berlinois peu après la chute du Mur.",
    thumbnail_url: thumb("u5MxTb2VqRn"),
    duration_seconds: 524,
    view_count: 12000,
    like_count: 980,
    published_at: "2018-09-09",
    youtube_url: url("u5MxTb2VqRn"),
    embed_allowed: true,
    status: "approved",
    rarity_score: 89,
    quality_score: 80,
    discovery_score: 91,
    sample_score: 60,
    ai_summary:
      "Techno brute et répétitive, image granuleuse, ambiance de club naissant dans le Berlin post-réunification.",
    ai_reason:
      "Document rare sur la scène techno berlinoise des débuts, faible circulation, forte valeur culturelle et rythmique.",
    mood: "nocturne",
    genre: "techno",
    country: "Allemagne",
    decade: "1990s",
    tags: ["techno", "club", "archive"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-010",
    youtube_video_id: "p9WcHl6ZmDf",
    title: "Field recording : pluie sur un toit de tôle, Amazonie",
    channel_name: "Terra Sons",
    channel_id: "ch-terra-sons",
    description:
      "Enregistrement ambiant d'une averse tropicale, capté près d'un village en bordure de forêt amazonienne.",
    thumbnail_url: thumb("p9WcHl6ZmDf"),
    duration_seconds: 620,
    view_count: 4100,
    like_count: 300,
    published_at: "2023-01-20",
    youtube_url: url("p9WcHl6ZmDf"),
    embed_allowed: true,
    status: "approved",
    rarity_score: 70,
    quality_score: 88,
    discovery_score: 60,
    sample_score: 25,
    ai_summary:
      "Texture sonore apaisante, pluie continue sur tôle, idéale pour une ambiance nocturne ou méditative.",
    ai_reason:
      "Qualité d'enregistrement élevée, contenu naturel rarement mis en avant par les algorithmes classiques.",
    mood: "apaisant",
    genre: "ambient",
    country: "Brésil",
    decade: "2010s",
    tags: ["field recording", "nature", "ambient"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-011",
    youtube_video_id: "k3RtQm8NxYv",
    title: "Groupe de rock garage lycéen, cassette autoproduite 1979",
    channel_name: "Basement Archive",
    channel_id: "ch-basement-archive",
    description:
      "Répétition captée dans un garage, cassette autoproduite jamais commercialisée.",
    thumbnail_url: thumb("k3RtQm8NxYv"),
    duration_seconds: 205,
    view_count: 540,
    like_count: 40,
    published_at: "2021-08-11",
    youtube_url: url("k3RtQm8NxYv"),
    embed_allowed: true,
    status: "pending",
    rarity_score: 84,
    quality_score: 65,
    discovery_score: 82,
    sample_score: 55,
    ai_summary:
      "Rock garage brut, prise de son amateur, énergie adolescente intacte.",
    ai_reason:
      "Bon potentiel de découverte mais qualité audio inégale — en attente de validation manuelle avant diffusion.",
    mood: "brut",
    genre: "garage rock",
    country: "États-Unis",
    decade: "1970s",
    tags: ["garage rock", "cassette", "amateur"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-012",
    youtube_video_id: "d6JpWs1FbTc",
    title: "Reprise a cappella dans une cour d'immeuble, Naples",
    channel_name: "Vicoli Sonori",
    channel_id: "ch-vicoli-sonori",
    description:
      "Chant traditionnel napolitain repris a cappella dans une cour intérieure, filmé au téléphone.",
    thumbnail_url: thumb("d6JpWs1FbTc"),
    duration_seconds: 142,
    view_count: 2100,
    like_count: 190,
    published_at: "2024-05-05",
    youtube_url: url("d6JpWs1FbTc"),
    embed_allowed: true,
    status: "pending",
    rarity_score: 60,
    quality_score: 72,
    discovery_score: 68,
    sample_score: 15,
    ai_summary:
      "Voix chaude, acoustique naturelle de la cour, chant traditionnel transmis à l'oreille.",
    ai_reason:
      "Belle découverte culturelle, en attente de vérification des droits sur le chant traditionnel interprété.",
    mood: "chaleureux",
    genre: "chant traditionnel",
    country: "Italie",
    decade: "2020s",
    tags: ["a cappella", "tradition", "Naples"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-013",
    youtube_video_id: "z1XyQe7HgAo",
    title: "Compilation de publicités non datées",
    channel_name: "Unknown Upload",
    channel_id: "ch-unknown-upload",
    description: "Montage flou de publicités sans source ni contexte identifiable.",
    thumbnail_url: thumb("z1XyQe7HgAo"),
    duration_seconds: 88,
    view_count: 300,
    like_count: 2,
    published_at: "2024-02-01",
    youtube_url: url("z1XyQe7HgAo"),
    embed_allowed: true,
    status: "rejected",
    rarity_score: 40,
    quality_score: 20,
    discovery_score: 10,
    sample_score: 5,
    ai_summary: "Montage sans cohérence éditoriale, qualité d'image très dégradée.",
    ai_reason:
      "Refusée : contenu hors sujet, absence de source identifiable, aucun intérêt culturel ou musical décelable.",
    mood: "indéfini",
    genre: "inconnu",
    country: "Inconnu",
    decade: "Inconnu",
    tags: ["rejeté"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "vid-014",
    youtube_video_id: "q0BnMv5TdSk",
    title: "Live stream abandonné, flux coupé",
    channel_name: "Dead Signal",
    channel_id: "ch-dead-signal",
    description: "Retransmission en direct interrompue, vidéo désormais indisponible à l'intégration.",
    thumbnail_url: thumb("q0BnMv5TdSk"),
    duration_seconds: 0,
    view_count: 12,
    like_count: 0,
    published_at: "2023-11-30",
    youtube_url: url("q0BnMv5TdSk"),
    embed_allowed: false,
    status: "unavailable",
    rarity_score: 50,
    quality_score: 10,
    discovery_score: 5,
    sample_score: 0,
    ai_summary: "Flux coupé avant la fin, lecture impossible.",
    ai_reason:
      "Marquée indisponible automatiquement : la vidéo ne peut plus être intégrée (retirée ou restreinte par son auteur).",
    mood: "indéfini",
    genre: "inconnu",
    country: "Inconnu",
    decade: "2020s",
    tags: ["indisponible"],
    created_at: now,
    updated_at: now,
  },
];
